# ------------------------------------------------------------------------------------------------------
# sidplayweb
#
# Erstellt dieses Image:
# cd net.teufel.sidhub.db
# docker build -f Dockerfile-sidplayweb -t mteufel/sidplayweb .
#
# Startet Bash in Image:
#  docker run -d -p 7788:7788 --name sidplay mteufel/sidplayweb
#
#
# Raeumt das lokale Docker-Sytem komplett auf (Alle Images, Container, ... werden geloescht):
# docker system prune -a
#
# Aenderunghsistorie:
# Wann        Wer       Was
# 12.05.2018 mteufel   Basisimage erstellt
# ------------------------------------------------------------------------------------------------------

FROM mteufel/debian-stretch-java

MAINTAINER Marc Teufel <teufel.marc@gmail.com>

RUN apt-get update

RUN useradd -ms /bin/bash user
WORKDIR /home/user
USER user
ENV JAVA_HOME /usr/java/jdk1.8.0_172
ENV PATH .:$JAVA_HOME/bin:$PATH

RUN rm -rf sidplayweb/ && mkdir -p sidplayweb

ADD sidplayweb-swarm.jar sidplayweb/sidplayweb-swarm.jar


ENTRYPOINT java -jar sidplayweb/sidplayweb-swarm.jar -Djava.net.preferIPv4Stack=true


EXPOSE 7788
