# =======================================================================================================
# Image:
#    Debian / Java 1.8.0u172 / H2-DB
#
#
# Wichtige Docker-Commands:
#    docker build -f Dockerfile-sidhubdb -t mteufel/sidhubdb .
#    docker run -d -v /home/marc/sidhubdb:/home/sidhub/sidhubdb-data -p 9101:9101 --name sidhubdb  mteufel/sidhubdb
#    docker run -i -t -v /home/marc/sidhubdb:/home/sidhubdb/sidhubdb-data mteufel/sidhubdb /bin/bash
#    docker system prune -a
#    docker images
#
# Änderunghistorie:
# Wann        Wer        Was
# 01.04.2017  mteufel    Basisimage erstellt
# =======================================================================================================

FROM debian:stretch-slim

MAINTAINER Marc Teufel <teufel.marc@gmail.com>

LABEL maintainer="Marc Teufel, hama GmbH & Co KG" description="Image: Debian / Java 1.8.0u172 / H2-DB"

ENV SIG a58eab1ec242421181065cdc37240b08

ENV PKG server-jre

RUN apt-get update && apt-get install -y curl \
    && rm -rf /usr/java/ && mkdir -p /usr/java \
    && curl -jkSLH "Cookie: oraclelicense=accept-securebackup-cookie" -o /usr/java/"${PKG}"-8u172-linux-x64.tar.gz http://download.oracle.com/otn-pub/java/jdk/8u172-b11/"${SIG}"/"${PKG}"-8u172-linux-x64.tar.gz \
    && tar xvf /usr/java/"${PKG}"-8u172-linux-x64.tar.gz -C /usr/java/ \
    && rm /usr/java/"${PKG}"-8u172-linux-x64.tar.gz

# Als Ergebnis haben wir jetzt eine Java-Installation im Order /usr/java/jdk1.8.0_172

ENV JAVA_HOME /usr/java/jdk1.8.0_172
ENV PATH .:$JAVA_HOME/bin:$PATH


# ----------------------------------------------------------
# Confluence User anlegen
# ----------------------------------------------------------

RUN useradd -ms /bin/bash sidhubdb

WORKDIR /home/sidhubdb

USER sidhubdb

# ----------------------------------------------------------
# Datenbank "installieren"
# ----------------------------------------------------------

# COPY h2-1.4.197.jar /home/sidhubdb
COPY sidplayweb-swarm.jar /home/sidhubdb

# ----------------------------------------------------------
# Datenbank starten, das Datenvolume kommt von außen
# ----------------------------------------------------------

#ENTRYPOINT java -Dh2.socketConnectTimeout=100000 -cp  /home/sidhubdb/h2-1.4.197.jar org.h2.tools.Server -tcpAllowOthers -tcpPort 9101 -baseDir /home/sidhubdb/sidhub-data
#EXPOSE 9101

ENTRYPOINT java -jar /home/sidhubdb/sidplayweb-swarm.jar -Djava.net.preferIPv4Stack=true

EXPOSE 7788