# ------------------------------------------------------------------------------------------------------
# Basis Debian 9 (Stretch) Linux Docker Image mit Java 8_161 (server-jre)
#
# Erstellt dieses Image:
# cd net.teufel.sidhub.db
# docker build -f Dockerfile-debian-stretch-java -t mteufel/debian-stretch-java .
#
# Startet Bash in Image:
#  docker run -i -v /Users/marcteufel/web-prj/test:/run/test  -t mteufel/debian-stretch-java /bin/bash
#
# Raeumt das lokale Docker-Sytem komplett auf (Alle Images, Container, ... werden geloescht):
# docker system prune -a    
#
# Aenderungshistorie:
# Wann        Wer       Was
# 01.04.2018  mteufel   Basisimage erstellt
# 12.05.2018  mteufel   Umstellung auf JDK 10.0.1
# ------------------------------------------------------------------------------------------------------

FROM debian:stretch-slim

MAINTAINER Marc Teufel <teufel.marc@gmail.com>

# Java 10
#
#ENV SIG fb4372174a714e6b8c52526dc134031e
#
#ENV PKG serverjre
#RUN apt-get update && apt-get install -y curl \
#    && rm -rf /usr/java/ && mkdir -p /usr/java \
#    && curl -jkSLH "Cookie: oraclelicense=accept-securebackup-cookie" -o /usr/java/"${PKG}"-10.0.1-linux-x64.tar.gz http://download.oracle.com/otn-pub/java/jdk/10.0.1+10/"${SIG}"/"${PKG}"-10.0.1_linux-x64_bin.tar.gz \
#    && tar xvf /usr/java/"${PKG}"-10.0.1-linux-x64.tar.gz -C /usr/java/ \
#    && rm /usr/java/"${PKG}"-10.0.1-linux-x64.tar.gz
# Als Ergebnis haben wir jetzt eine Java-Installation im Order /usr/java/
#ENV JAVA_HOME /usr/java/jdk-10.0.1
#ENV PATH .:$JAVA_HOME/bin:$PATH


ENV SIG a58eab1ec242421181065cdc37240b08

ENV PKG server-jre

RUN apt-get update && apt-get install -y curl \
    && rm -rf /usr/java/ && mkdir -p /usr/java \
    && curl -jkSLH "Cookie: oraclelicense=accept-securebackup-cookie" -o /usr/java/"${PKG}"-8u172-linux-x64.tar.gz http://download.oracle.com/otn-pub/java/jdk/8u172-b11/"${SIG}"/"${PKG}"-8u172-linux-x64.tar.gz \
    && tar xvf /usr/java/"${PKG}"-8u172-linux-x64.tar.gz -C /usr/java/ \
    && rm /usr/java/"${PKG}"-8u172-linux-x64.tar.gz

# Als Ergebnis haben wir jetzt eine Java-Installation im Order /usr/java/jdk1.8.0_172

ENV JAVA_HOME /usr/java/jdk1.8.0_172
ENV PATH .:$JAVA_HOME/bin:$PATH




#http://download.oracle.com/otn-pub/java/jdk/8u172-b11/a58eab1ec242421181065cdc37240b08/server-jre-8u172-linux-x64.tar.gz