create table SID (
    ID INTEGER PRIMARY KEY ASC,
    TITLE TEXT,
    AUTHOR TEXT,
    RELEASE TEXT,
    NO_SUBTUNES INTEGER,
    PREFERRED_MODEL TEXT
);

create table SID_FILES (
    SID_ID INTEGER,
    PATH TEXT,
    FILE_NAME TEXT,
    FILE_SIZE_COMPRESSED INTEGER,
    FILE_SIZE_UNCOMPRESSED INTEGER,
    FILE BLOB
);

create table TYPE (
    ID INTEGER PRIMARY KEY ASC,
    TYPE TEXT
);

create table SID_IDX (
    SID_ID INTEGER,
    TYPE_ID INTEGER,
    VALUE TEXT
);

create table SID_SONGLENGTH (
  SID_ID INTEGER,
	NO_SUBTUNE INTEGER,
	LENGTH TEXT
);